server.port=${SERVER_PORT:8082}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/voting_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:voting_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:voting_pass}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:voting}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:voting_pass}

spring.redis.host=${SPRING_REDIS_HOST:localhost}
spring.redis.port=${SPRING_REDIS_PORT:6379}

management.endpoints.web.exposure.include=health,metrics,prometheus
management.metrics.tags.application=voting-service
